from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from app.models.models import Customer, Appointment
from app.core.logger import logger
from app.tools.registry import ToolRegistry
import datetime

@ToolRegistry.register(
    name="book_appointment",
    description="Schedules and registers a new calendar appointment in the system.",
    parameters={
        "type": "object",
        "properties": {
            "organization_id": {"type": "integer"},
            "phone": {"type": "string"},
            "name": {"type": "string"},
            "datetime_str": {"type": "string", "description": "Date and time in format YYYY-MM-DD HH:MM"},
            "title": {"type": "string"}
        },
        "required": ["organization_id", "phone", "name", "datetime_str"]
    },
    required_permissions=["agent"]
)
async def book_appointment(
    organization_id: int,
    phone: str,
    name: str,
    datetime_str: str,  # Expected format: "YYYY-MM-DD HH:MM" (e.g. "2026-07-15 10:00")
    title: str,
    db: AsyncSession
) -> dict:
    logger.info(f"Tool Run: book_appointment for {phone} at {datetime_str}")
    
    # 1. Parse date and time
    try:
        start_time = datetime.datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")
        end_time = start_time + datetime.timedelta(minutes=30)  # Standard 30-min discovery session
    except ValueError:
        logger.warning(f"Failed to parse datetime parameters: {datetime_str}")
        return {
            "success": False,
            "message": "Invalid date-time format. Please use YYYY-MM-DD HH:MM (e.g., '2026-07-15 13:30')."
        }
        
    # 2. Get customer
    cust_res = await db.execute(select(Customer).filter(Customer.phone == phone))
    customer = cust_res.scalar()
    if not customer:
        customer = Customer(
            name=name,
            phone=phone,
            organization_id=organization_id
        )
        db.add(customer)
        await db.flush()
        
    # 3. Create Appointment booking
    appt = Appointment(
        organization_id=organization_id,
        customer_id=customer.id,
        title=title or "Vocentra Consultation Call",
        start_time=start_time,
        end_time=end_time,
        status="scheduled",
        notes="Automated booking generated by voice AI agent during call."
    )
    db.add(appt)
    await db.flush()
    
    # Trigger Google Calendar invite creation
    from app.integrations import GoogleCalendarConnector
    meet_link = await GoogleCalendarConnector.create_meeting_invite(appt.title, start_time)
    appt.notes = f"Google Meet URL: {meet_link}\nAutomated booking generated by voice AI agent."
    await db.commit()
    
    logger.info(f"Booking locked: appt_id={appt.id} scheduled for {customer.name} at {start_time}")
    return {
        "success": True,
        "appointment_id": appt.id,
        "start_time": start_time.isoformat(),
        "google_meet_url": meet_link,
        "message": f"Successfully booked {appt.title} on {start_time.strftime('%B %d, %Y')} at {start_time.strftime('%I:%M %p')}. Google Meet Link: {meet_link}"
    }
