"""add_campaign_lead_metrics

Revision ID: 369fcca463b3
Revises: 037025cd7d41
Create Date: 2026-07-21 11:46:48.826521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369fcca463b3'
down_revision: Union[str, None] = '037025cd7d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_leads', sa.Column('assistant_id', sa.String(), nullable=True))
    op.add_column('campaign_leads', sa.Column('phone_number_id', sa.String(), nullable=True))
    op.add_column('campaign_leads', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_leads', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('campaign_leads', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('campaign_leads', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('campaign_leads', sa.Column('recording_url', sa.String(), nullable=True))
    op.add_column('campaign_leads', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('campaign_leads', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('campaign_leads', sa.Column('ended_reason', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('call_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'call_delay')
    op.drop_column('campaign_leads', 'ended_reason')
    op.drop_column('campaign_leads', 'transcript')
    op.drop_column('campaign_leads', 'summary')
    op.drop_column('campaign_leads', 'recording_url')
    op.drop_column('campaign_leads', 'cost')
    op.drop_column('campaign_leads', 'duration')
    op.drop_column('campaign_leads', 'ended_at')
    op.drop_column('campaign_leads', 'started_at')
    op.drop_column('campaign_leads', 'phone_number_id')
    op.drop_column('campaign_leads', 'assistant_id')
    # ### end Alembic commands ###
